const API_CALL_REQUEST = "cwa/location/API_CALL_REQUEST";
const API_CALL_SUCCESS = "cwa/location/API_CALL_SUCCESS";
const API_CALL_FAILURE = "cwa/location/API_CALL_FAILURE";

export { API_CALL_REQUEST, API_CALL_SUCCESS, API_CALL_FAILURE }; 